name: geofence_mobile_flutter
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.6.1

  # Routing
  go_router: ^14.6.2

  # HTTP Client
  dio: ^5.7.0

  # Device Info
  device_info_plus: ^10.1.2
  battery_plus: ^6.0.3

  # Storage
  shared_preferences: ^2.3.3

  # Location
  geolocator: ^13.0.2
  permission_handler: ^11.3.1

  # Firebase (para notificaciones)
  firebase_core: ^3.10.0
  firebase_messaging: ^15.2.0
  flutter_local_notifications: ^18.0.1

  # Maps (descomenta el que vayas a usar)
  # google_maps_flutter: ^2.9.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  # Background Service
  workmanager: ^0.9.0+3
  flutter_background_service: ^5.0.10
  flutter_background_service_android: ^6.2.7

  # Theme & Fonts
  flex_color_scheme: ^8.0.2
  google_fonts: ^6.2.1

  # Animations
  flutter_animate: ^4.5.2

  # Icons
  cupertino_icons: ^1.0.8

  # Environment variables
  flutter_dotenv: ^5.2.1
  firebase_analytics: ^11.6.0
  mobile_scanner: ^7.1.3
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

# Configuración del ícono de la app
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/geofencing_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/geofencing_logo.png"
  min_sdk_android: 21


flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/geofencing_logo.png
    - assets/geofencing_banner.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

